version: '3.9'
services:
  # api:
  #   build:
  #     context: ./src
  #     dockerfile: ProductManagement.API/Dockerfile
  #   ports:
  #     - "8080:8081" # HTTP
  #     - "8443:443"  # HTTPS
  #   depends_on:
  #     - db
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_URLS=http://+:8081;https://+:443
  #     - ConnectionStrings__DefaultConnection=Host=db;Database=ProductManagementDb;Username=yourusername;Password=yourpassword
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:8081"] # Updated to match port
  #     timeout: 5s
  #     retries: 3
  #   restart: always # Added restart policy
  db:
    container_name: postgres
    image: postgres:latest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U yourusername -d ProductManagementDb"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=yourusername
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=ProductManagementDb
    ports:
      - "5432:5432"
    # volumes:
    #   - db-data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - "8082:8080" # Updated to avoid port conflicts
volumes:
  db-data: