name: .NET Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SOLUTION_FILE: src/ProductManagement.sln

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_FILE }}

    - name: Build
      run: dotnet build ${{ env.SOLUTION_FILE }} --configuration Release --no-restore
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1

    - name: Run static code analysis
      run: dotnet build ${{ env.SOLUTION_FILE }} --configuration Release --no-restore -warnaserror
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1

    - name: Run tests
      run: dotnet test ${{ env.SOLUTION_FILE }} --no-restore --verbosity normal
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
