name: .NET Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SOLUTION_FILE: src/ProductManagement.sln

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_FILE }}

    - name: Build and Run static code analysis
      run: dotnet build ${{ env.SOLUTION_FILE }} --configuration Release --no-restore -warnaserror
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1

    - name: Run tests with coverage
      run: |
        sudo apt-get update
        sudo apt-get install -y jq        
        dotnet test ${{ env.SOLUTION_FILE }} --no-restore --verbosity normal --collect:"XPlat Code Coverage" --logger "trx;LogFileName=test_results.trx" --results-directory ./TestResults
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1

    - name: Publish test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Test Results
        path: '**/test_results.trx'

    - name: Report test results
      if: always()
      uses: dorny/test-reporter@v1
      with:
        name: Test Results
        path: '**/test_results.trx'
        reporter: dotnet-trx

    - name: Parse coverage report
      id: coverage
      run: |       
        COVERAGE_FILE=$(find ./TestResults -type f -name "*.coverage.cobertura.xml")
        if [ -z "$COVERAGE_FILE" ]; then
          echo "Coverage files not found."
          exit 1
        fi
        COVERAGE_PERCENTAGE=$(cat $COVERAGE_FILE | jq '.[] | select(.name == "Line") | .coveredpercent')
        echo "Coverage Percentage: $COVERAGE_PERCENTAGE"
        echo "COVERAGE_PERCENTAGE=$COVERAGE_PERCENTAGE" >> $GITHUB_ENV

    - name: Fail if coverage is below 50%
      if: ${{ env.COVERAGE_PERCENTAGE }} < 50
      run: |
        echo "Code coverage is below 50%. Failing the workflow."
        exit 1
